spring:
  application:
    name: ai-imageAgent
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_agent?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  profiles:
    active: prod
server:
  port: 8123
  servlet:
    context-path: /api


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ai.imageagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
